name: CI
on:
  pull_request:
  push:
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
        setScala3: [ "", "SetScala3"]
    steps:
      - uses: actions/checkout@v2
      - name: Docker pull
        run: docker-compose pull
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: coursier/cache-action@v5
      - name: Test
        run: ./sbt ${{ matrix.setScala3 }} stage test
