name: Deploy to Heroku
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: coursier/cache-action@v5
      - name: Deploy to Heroku
        run: HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} ./sbt SetScala3 stage deployHeroku
